"""Add session_invites table

Revision ID: 6358987d0b2f
Revises: move_single_resp_to_q
Create Date: 2025-12-03 21:39:14.167188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6358987d0b2f'
down_revision: Union[str, None] = 'move_single_resp_to_q'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_invite_per_email', 'session_invites', ['email', 'status'], unique=False)
    op.create_index(op.f('ix_session_invites_code'), 'session_invites', ['code'], unique=True)
    op.create_index(op.f('ix_session_invites_email'), 'session_invites', ['email'], unique=False)
    op.create_index(op.f('ix_session_invites_expires_at'), 'session_invites', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_invites_session_id'), 'session_invites', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_invites_status'), 'session_invites', ['status'], unique=False)
    op.alter_column('poll_questions', 'single_response',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_resources_status', table_name='resources')
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.create_index('idx_resources_status', 'resources', ['status'], unique=False)
    op.alter_column('poll_questions', 'single_response',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_session_invites_status'), table_name='session_invites')
    op.drop_index(op.f('ix_session_invites_session_id'), table_name='session_invites')
    op.drop_index(op.f('ix_session_invites_expires_at'), table_name='session_invites')
    op.drop_index(op.f('ix_session_invites_email'), table_name='session_invites')
    op.drop_index(op.f('ix_session_invites_code'), table_name='session_invites')
    op.drop_index('idx_pending_invite_per_email', table_name='session_invites')
    op.drop_table('session_invites')
    # ### end Alembic commands ###

